// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_add_5fcontact_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_add_5fcontact_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_2eproto;
namespace AddCont {
class AddContactRequest;
struct AddContactRequestDefaultTypeInternal;
extern AddContactRequestDefaultTypeInternal _AddContactRequest_default_instance_;
class AddContactRequest_Phone;
struct AddContactRequest_PhoneDefaultTypeInternal;
extern AddContactRequest_PhoneDefaultTypeInternal _AddContactRequest_Phone_default_instance_;
class AddContactResponse;
struct AddContactResponseDefaultTypeInternal;
extern AddContactResponseDefaultTypeInternal _AddContactResponse_default_instance_;
}  // namespace AddCont
PROTOBUF_NAMESPACE_OPEN
template<> ::AddCont::AddContactRequest* Arena::CreateMaybeMessage<::AddCont::AddContactRequest>(Arena*);
template<> ::AddCont::AddContactRequest_Phone* Arena::CreateMaybeMessage<::AddCont::AddContactRequest_Phone>(Arena*);
template<> ::AddCont::AddContactResponse* Arena::CreateMaybeMessage<::AddCont::AddContactResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AddCont {

enum AddContactRequest_Phone_PhoneType : int {
  AddContactRequest_Phone_PhoneType_MP = 0,
  AddContactRequest_Phone_PhoneType_TEL = 1,
  AddContactRequest_Phone_PhoneType_AddContactRequest_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AddContactRequest_Phone_PhoneType_AddContactRequest_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AddContactRequest_Phone_PhoneType_IsValid(int value);
constexpr AddContactRequest_Phone_PhoneType AddContactRequest_Phone_PhoneType_PhoneType_MIN = AddContactRequest_Phone_PhoneType_MP;
constexpr AddContactRequest_Phone_PhoneType AddContactRequest_Phone_PhoneType_PhoneType_MAX = AddContactRequest_Phone_PhoneType_TEL;
constexpr int AddContactRequest_Phone_PhoneType_PhoneType_ARRAYSIZE = AddContactRequest_Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AddContactRequest_Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& AddContactRequest_Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AddContactRequest_Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AddContactRequest_Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AddContactRequest_Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool AddContactRequest_Phone_PhoneType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AddContactRequest_Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AddContactRequest_Phone_PhoneType>(
    AddContactRequest_Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class AddContactRequest_Phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AddCont.AddContactRequest.Phone) */ {
 public:
  inline AddContactRequest_Phone() : AddContactRequest_Phone(nullptr) {}
  ~AddContactRequest_Phone() override;
  explicit PROTOBUF_CONSTEXPR AddContactRequest_Phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddContactRequest_Phone(const AddContactRequest_Phone& from);
  AddContactRequest_Phone(AddContactRequest_Phone&& from) noexcept
    : AddContactRequest_Phone() {
    *this = ::std::move(from);
  }

  inline AddContactRequest_Phone& operator=(const AddContactRequest_Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactRequest_Phone& operator=(AddContactRequest_Phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddContactRequest_Phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddContactRequest_Phone* internal_default_instance() {
    return reinterpret_cast<const AddContactRequest_Phone*>(
               &_AddContactRequest_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddContactRequest_Phone& a, AddContactRequest_Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactRequest_Phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactRequest_Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddContactRequest_Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddContactRequest_Phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddContactRequest_Phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddContactRequest_Phone& from) {
    AddContactRequest_Phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactRequest_Phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AddCont.AddContactRequest.Phone";
  }
  protected:
  explicit AddContactRequest_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AddContactRequest_Phone_PhoneType PhoneType;
  static constexpr PhoneType MP =
    AddContactRequest_Phone_PhoneType_MP;
  static constexpr PhoneType TEL =
    AddContactRequest_Phone_PhoneType_TEL;
  static inline bool PhoneType_IsValid(int value) {
    return AddContactRequest_Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    AddContactRequest_Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    AddContactRequest_Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    AddContactRequest_Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return AddContactRequest_Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return AddContactRequest_Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PhoneType* value) {
    return AddContactRequest_Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_number();
  PROTOBUF_NODISCARD std::string* release_number();
  void set_allocated_number(std::string* number);
  private:
  const std::string& _internal_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .AddCont.AddContactRequest.Phone.PhoneType type = 2;
  void clear_type();
  ::AddCont::AddContactRequest_Phone_PhoneType type() const;
  void set_type(::AddCont::AddContactRequest_Phone_PhoneType value);
  private:
  ::AddCont::AddContactRequest_Phone_PhoneType _internal_type() const;
  void _internal_set_type(::AddCont::AddContactRequest_Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:AddCont.AddContactRequest.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_5fcontact_2eproto;
};
// -------------------------------------------------------------------

class AddContactRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AddCont.AddContactRequest) */ {
 public:
  inline AddContactRequest() : AddContactRequest(nullptr) {}
  ~AddContactRequest() override;
  explicit PROTOBUF_CONSTEXPR AddContactRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddContactRequest(const AddContactRequest& from);
  AddContactRequest(AddContactRequest&& from) noexcept
    : AddContactRequest() {
    *this = ::std::move(from);
  }

  inline AddContactRequest& operator=(const AddContactRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactRequest& operator=(AddContactRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddContactRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddContactRequest* internal_default_instance() {
    return reinterpret_cast<const AddContactRequest*>(
               &_AddContactRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AddContactRequest& a, AddContactRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddContactRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddContactRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddContactRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddContactRequest& from) {
    AddContactRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AddCont.AddContactRequest";
  }
  protected:
  explicit AddContactRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AddContactRequest_Phone Phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneFieldNumber = 3,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated .AddCont.AddContactRequest.Phone phone = 3;
  int phone_size() const;
  private:
  int _internal_phone_size() const;
  public:
  void clear_phone();
  ::AddCont::AddContactRequest_Phone* mutable_phone(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AddCont::AddContactRequest_Phone >*
      mutable_phone();
  private:
  const ::AddCont::AddContactRequest_Phone& _internal_phone(int index) const;
  ::AddCont::AddContactRequest_Phone* _internal_add_phone();
  public:
  const ::AddCont::AddContactRequest_Phone& phone(int index) const;
  ::AddCont::AddContactRequest_Phone* add_phone();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AddCont::AddContactRequest_Phone >&
      phone() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:AddCont.AddContactRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AddCont::AddContactRequest_Phone > phone_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_5fcontact_2eproto;
};
// -------------------------------------------------------------------

class AddContactResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AddCont.AddContactResponse) */ {
 public:
  inline AddContactResponse() : AddContactResponse(nullptr) {}
  ~AddContactResponse() override;
  explicit PROTOBUF_CONSTEXPR AddContactResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddContactResponse(const AddContactResponse& from);
  AddContactResponse(AddContactResponse&& from) noexcept
    : AddContactResponse() {
    *this = ::std::move(from);
  }

  inline AddContactResponse& operator=(const AddContactResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactResponse& operator=(AddContactResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddContactResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddContactResponse* internal_default_instance() {
    return reinterpret_cast<const AddContactResponse*>(
               &_AddContactResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AddContactResponse& a, AddContactResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddContactResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddContactResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddContactResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddContactResponse& from) {
    AddContactResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AddCont.AddContactResponse";
  }
  protected:
  explicit AddContactResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorDescFieldNumber = 2,
    kUidFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // string errorDesc = 2;
  void clear_errordesc();
  const std::string& errordesc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errordesc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errordesc();
  PROTOBUF_NODISCARD std::string* release_errordesc();
  void set_allocated_errordesc(std::string* errordesc);
  private:
  const std::string& _internal_errordesc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errordesc(const std::string& value);
  std::string* _internal_mutable_errordesc();
  public:

  // string uid = 3;
  void clear_uid();
  const std::string& uid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uid();
  PROTOBUF_NODISCARD std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  private:
  const std::string& _internal_uid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:AddCont.AddContactResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errordesc_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_5fcontact_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddContactRequest_Phone

// string number = 1;
inline void AddContactRequest_Phone::clear_number() {
  _impl_.number_.ClearToEmpty();
}
inline const std::string& AddContactRequest_Phone::number() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactRequest.Phone.number)
  return _internal_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactRequest_Phone::set_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AddCont.AddContactRequest.Phone.number)
}
inline std::string* AddContactRequest_Phone::mutable_number() {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:AddCont.AddContactRequest.Phone.number)
  return _s;
}
inline const std::string& AddContactRequest_Phone::_internal_number() const {
  return _impl_.number_.Get();
}
inline void AddContactRequest_Phone::_internal_set_number(const std::string& value) {
  
  _impl_.number_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactRequest_Phone::_internal_mutable_number() {
  
  return _impl_.number_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactRequest_Phone::release_number() {
  // @@protoc_insertion_point(field_release:AddCont.AddContactRequest.Phone.number)
  return _impl_.number_.Release();
}
inline void AddContactRequest_Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  _impl_.number_.SetAllocated(number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:AddCont.AddContactRequest.Phone.number)
}

// .AddCont.AddContactRequest.Phone.PhoneType type = 2;
inline void AddContactRequest_Phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::AddCont::AddContactRequest_Phone_PhoneType AddContactRequest_Phone::_internal_type() const {
  return static_cast< ::AddCont::AddContactRequest_Phone_PhoneType >(_impl_.type_);
}
inline ::AddCont::AddContactRequest_Phone_PhoneType AddContactRequest_Phone::type() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactRequest.Phone.type)
  return _internal_type();
}
inline void AddContactRequest_Phone::_internal_set_type(::AddCont::AddContactRequest_Phone_PhoneType value) {
  
  _impl_.type_ = value;
}
inline void AddContactRequest_Phone::set_type(::AddCont::AddContactRequest_Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:AddCont.AddContactRequest.Phone.type)
}

// -------------------------------------------------------------------

// AddContactRequest

// string name = 1;
inline void AddContactRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& AddContactRequest::name() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AddCont.AddContactRequest.name)
}
inline std::string* AddContactRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:AddCont.AddContactRequest.name)
  return _s;
}
inline const std::string& AddContactRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void AddContactRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactRequest::release_name() {
  // @@protoc_insertion_point(field_release:AddCont.AddContactRequest.name)
  return _impl_.name_.Release();
}
inline void AddContactRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:AddCont.AddContactRequest.name)
}

// int32 age = 2;
inline void AddContactRequest::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t AddContactRequest::_internal_age() const {
  return _impl_.age_;
}
inline int32_t AddContactRequest::age() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactRequest.age)
  return _internal_age();
}
inline void AddContactRequest::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void AddContactRequest::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:AddCont.AddContactRequest.age)
}

// repeated .AddCont.AddContactRequest.Phone phone = 3;
inline int AddContactRequest::_internal_phone_size() const {
  return _impl_.phone_.size();
}
inline int AddContactRequest::phone_size() const {
  return _internal_phone_size();
}
inline void AddContactRequest::clear_phone() {
  _impl_.phone_.Clear();
}
inline ::AddCont::AddContactRequest_Phone* AddContactRequest::mutable_phone(int index) {
  // @@protoc_insertion_point(field_mutable:AddCont.AddContactRequest.phone)
  return _impl_.phone_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AddCont::AddContactRequest_Phone >*
AddContactRequest::mutable_phone() {
  // @@protoc_insertion_point(field_mutable_list:AddCont.AddContactRequest.phone)
  return &_impl_.phone_;
}
inline const ::AddCont::AddContactRequest_Phone& AddContactRequest::_internal_phone(int index) const {
  return _impl_.phone_.Get(index);
}
inline const ::AddCont::AddContactRequest_Phone& AddContactRequest::phone(int index) const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactRequest.phone)
  return _internal_phone(index);
}
inline ::AddCont::AddContactRequest_Phone* AddContactRequest::_internal_add_phone() {
  return _impl_.phone_.Add();
}
inline ::AddCont::AddContactRequest_Phone* AddContactRequest::add_phone() {
  ::AddCont::AddContactRequest_Phone* _add = _internal_add_phone();
  // @@protoc_insertion_point(field_add:AddCont.AddContactRequest.phone)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AddCont::AddContactRequest_Phone >&
AddContactRequest::phone() const {
  // @@protoc_insertion_point(field_list:AddCont.AddContactRequest.phone)
  return _impl_.phone_;
}

// -------------------------------------------------------------------

// AddContactResponse

// bool success = 1;
inline void AddContactResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool AddContactResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool AddContactResponse::success() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactResponse.success)
  return _internal_success();
}
inline void AddContactResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AddContactResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:AddCont.AddContactResponse.success)
}

// string errorDesc = 2;
inline void AddContactResponse::clear_errordesc() {
  _impl_.errordesc_.ClearToEmpty();
}
inline const std::string& AddContactResponse::errordesc() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactResponse.errorDesc)
  return _internal_errordesc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactResponse::set_errordesc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errordesc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AddCont.AddContactResponse.errorDesc)
}
inline std::string* AddContactResponse::mutable_errordesc() {
  std::string* _s = _internal_mutable_errordesc();
  // @@protoc_insertion_point(field_mutable:AddCont.AddContactResponse.errorDesc)
  return _s;
}
inline const std::string& AddContactResponse::_internal_errordesc() const {
  return _impl_.errordesc_.Get();
}
inline void AddContactResponse::_internal_set_errordesc(const std::string& value) {
  
  _impl_.errordesc_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactResponse::_internal_mutable_errordesc() {
  
  return _impl_.errordesc_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactResponse::release_errordesc() {
  // @@protoc_insertion_point(field_release:AddCont.AddContactResponse.errorDesc)
  return _impl_.errordesc_.Release();
}
inline void AddContactResponse::set_allocated_errordesc(std::string* errordesc) {
  if (errordesc != nullptr) {
    
  } else {
    
  }
  _impl_.errordesc_.SetAllocated(errordesc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errordesc_.IsDefault()) {
    _impl_.errordesc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:AddCont.AddContactResponse.errorDesc)
}

// string uid = 3;
inline void AddContactResponse::clear_uid() {
  _impl_.uid_.ClearToEmpty();
}
inline const std::string& AddContactResponse::uid() const {
  // @@protoc_insertion_point(field_get:AddCont.AddContactResponse.uid)
  return _internal_uid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactResponse::set_uid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:AddCont.AddContactResponse.uid)
}
inline std::string* AddContactResponse::mutable_uid() {
  std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:AddCont.AddContactResponse.uid)
  return _s;
}
inline const std::string& AddContactResponse::_internal_uid() const {
  return _impl_.uid_.Get();
}
inline void AddContactResponse::_internal_set_uid(const std::string& value) {
  
  _impl_.uid_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactResponse::_internal_mutable_uid() {
  
  return _impl_.uid_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactResponse::release_uid() {
  // @@protoc_insertion_point(field_release:AddCont.AddContactResponse.uid)
  return _impl_.uid_.Release();
}
inline void AddContactResponse::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  _impl_.uid_.SetAllocated(uid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:AddCont.AddContactResponse.uid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace AddCont

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::AddCont::AddContactRequest_Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::AddCont::AddContactRequest_Phone_PhoneType>() {
  return ::AddCont::AddContactRequest_Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_2eproto
